### ISSUE TITLE
Ulid should implement Serialize and Deserialize

### ISSUE THREAD

**Issue by oysterpack** [huxi/rusty_ulid#1]
Ulid should implement Serde's Serialize and Deserialize as an optional feature.

This will enhance the library's interoperability per Rust API Guidelines: [Data structures implement Serde's Serialize and Deserialize](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde)

**Comment by oysterpack** [comment]
I was about to make the change myself, when I saw it's already done. However, it's not yet been published to crates.io. 

When are you planning on releasing ?

**Comment by huxi** [comment]
@oysterpack I was unsure whether or not I implemented the `Deserialize` trait in a reasonable way... it's the first time I manually implemented it.
Do you have experience with it? Does it look reasonable to you? A could do a release later today.

**Comment by oysterpack** [comment]
I reviewed the code and unit tests. It looks perfect.

A release today would be great. Thanks.

**Comment by huxi** [comment]
@oysterpack I just released it as 0.8.0. Let me know if you run into any problems.

Cheers & thanks for the feedback!
