### ISSUE TITLE
BIGINT vs UUID vs ULID performance

### ISSUE THREAD

**Issue by ghost** [huxi/rusty_ulid#6]
Thank you for your work on this library. 

Would you have any feedback on the performance difference in Postgres DB for primary key on a table with 1 million records for read, write sorting between:

BIGINT
UUID v7
ULID

Particularly on multiple table join queries with either of above as PK and FK

**Comment by huxi** [comment]
Sorry, can't help you with that one. You'll have to benchmark your DB yourself.

A ULID is simply a 26 character string. You could also use binary representation (i.e. 16 bytes) but that's all up to you.

Both representations are sortable, which means that ULIDs generated "later" are "bigger".
